<?php

return [
        'variable' => [
            'SSE_ufaaddr' => ['subjectFrom->actualEntity->address','Адрес Местонахождения юр лица'],
            'SSE_umail' => ['command','Электронная почта'],
            'SSE_cnfu' => ['subjectFrom->actualEntity->fullName','Полное название организации'],
            'SSE_cnsh' => ['subjectFrom->actualEntity->fullName','Полное название организации'],
            'SSE_inn' => ['subjectFrom->actualEntity->inn','ИНН организации'],
            'SSE_ln' => ['subjectFrom->surname','Фамилия другие падежи'],
            'SSE_fn' => ['subjectFrom->name','Имя другие падежи'],
            'SSE_sn' => ['subjectFrom->patronymic','Отчество другие падежи'],
            'SSE_fns' => ['subjectFrom->fio','Сокращенная форма ФИО [Иванов И.И.]'],
            'SSE_ogrn' => ['subjectFrom->actualEntity->ogrn','ОГРН'],
            'SSE_uregaddr' => ['subjectFrom->actualEntity->address','Адрес регистрации юр лица'],
            'SSE_bd' => ['subjectFrom->birthday','Дата рождения'],
            'SSE_bp' => ['subjectFrom->actualPassport->birthplace','Место рождения'],
            'SSE_pasn' => ['subjectFrom->actualPassport->number','Серия и номер паспорта'],
            'SSE_pash' => ['subjectFrom->actualPassport->issuedBy','Кем выдан паспорт'],
            'SSE_pasd' => ['subjectFrom->actualPassport->dateIssued','Дата выдачи паспорта'],
            'SSE_pasc' => ['subjectFrom->actualPassport->code','Код подразделения паспорта'],
            'SSE_regaddrd' => ['subjectFrom->actualPassport->dateResidence','Дата регистрации'],
            'SSE_regaddr' => ['subjectFrom->actualPassport->placeResidence','Адрес регистрации'],
            'SSE_lisde' => ['subjectFrom->actuallicense->startText','Срок действия водительского удостоверения'],
            'SSE_lisn' => ['subjectFrom->actuallicense->number','Серия и номер водительского удостоверения'],
            'SSE_lish' => ['subjectFrom->actuallicense->issuedBy','Кем выдано водительское удостоверение'],
            'SSE_lisd' => ['command','Дата выдачи водительского удостоверения'],
            'SSE_phone' => ['subjectFrom->actualContact->phone','Номер телефона'],
            'SSE_mail' => ['command','Элетронная почта'],
            'SSE_accn' => ['subjectFrom->actualPayment->checkingAccount','Номер счёта'],
            'SSE_babik' => ['subjectFrom->actualPayment->bankBik','БИК банка'],
            'SSE_baaddr' => ['subjectFrom->actualPayment->address','Юридический адрес'],
            'SSE_bainn' => ['subjectFrom->actualPayment->bankInn','ИНН банка'],
            'SSE_corrch' => ['subjectFrom->actualPayment->correspondentAccount','к/сч'],
            'SSE_bafn' => ['subjectTo->actualPayment->name','Название филиала'],
            'SSE_ban' => ['subjectFrom->actualPayment->bankName','Наименование банка'],
            'SSE_ccn' => ['subjectFrom->payAccount->cardNumber','Номер карты'],
            
            'SCL_ufaaddr' => ['subjectTo->actualEntity->address','Адрес Местонахождения юр лица'],
            'SCL_umail' => ['command','Электронная почта'],
            'SCL_cn' => ['subjectTo->actualEntity->fullName','Название организацииы'],
            'SCL_ln' => ['subjectTo->surname','Фамилия арендатора другие падежи'],
            'SCL_fn' => ['subjectTo->name','Имя арендатора другие падежи'],
            'SCL_sn' => ['subjectTo->patronymic','Отчество арендатора другие падежи'],
            'SCL_fns' => ['subjectTo->fio','Сокращенная форма ФИО [Иванов И.И.]'],
            'SCL_bd' => ['subjectTo->birthdayText','Дата рождения арендатора'],
            'SCL_bp' => ['subjectTo->actualPassport->birthplace','Место рождения арендатора'],
            'SCL_pasn' => ['subjectTo->actualPassport->number','Серия и номер паспорта арендатора'],
            'SCL_pash' => ['subjectTo->actualPassport->issuedBy','Кем выдан паспорт'],
            'SCL_pasd' => ['subjectTo->actualPassport->dateIssuedText','Дата выдачи паспорта'],
            'SCL_pasc' => ['subjectTo->actualPassport->code','Код подразделения паспорта'],
            'SCL_regaddr' => ['subjectTo->actualPassport->placeResidence','Адрес регистрации арендатора'],
            'SCL_regaddrd' => ['subjectTo->actualPassport->dateResidenceText','Дата регистрации'],
            'SCL_addr' => ['subjectTo->actualPassport->placeResidence','Место жительства арендатора'],
            'SCL_lisn' => ['subjectTo->actuallicense->number','Серия и номер водительского удостоверения арендатора'],
            'SCL_lish' => ['subjectTo->actuallicense->issuedBy','Кем выдано водительское удостоверение'],
            'SCL_lisd' => ['subjectTo->actuallicense->startText','Дата выдачи водительского удостоверения'],
            'SCL_lisde' => ['subjectTo->actuallicense->finishText','Срок действия водительского удостоверения'],
            'SCL_phone' => ['subjectTo->actualContact->phone','Номер телефона Арендатора'],
            'SCL_mail' => ['command','Элетронная почта арендатора'],
            'SCL_accn' => ['subjectTo->actualPayment->checkingAccount','Номер счёта арендатора'],
            'SCL_babik' => ['subjectTo->actualPayment->bankBik','БИК банка арендатора'],
            'SCL_corrch' => ['subjectTo->actualPayment->correspondentAccount','к/сч'],
            'SCL_bainn' => ['subjectTo->actualPayment->bankInn','ИНН банка'],
            'SCL_baaddr' => ['subjectTo->actualPayment->address','Юридический адрес'],
            'SCL_bafn' => ['subjectTo->actualPayment->name','Название филиала'],
            'SCL_ban' => ['subjectTo->actualPayment->bankName','Наименование банка арендатора'],
            'SCL_ccn' => ['subjectTo->payAccount->cardNumber','Номер карты арендатора'],
            
            'CAR_Brand' => ['car->generation->model->brand->name','Марка автомобиля'],
            'CAR_Model' => ['car->generation->model->name','Модель автомобиля'],
            'CAR_VINn' => ['car->vin','VIN номер автомобиля'],
            'CAR_Y' => ['car->year','Год выпуска автомобиля'],
            'CAR_nick' => ['car->nickName','Nickname автомобиля'],
            
            'CAR_Power' => ['car->hp','Мощность двигателя'],
            'CAR_StNum' => ['sts->regNumber','Регистрационный номер'],
            'CAR_STSd' => ['sts->dateDocumentText','Дата выдачи СТС'],
            'CAR_STSn' => ['sts->number','Серия и Номер СТС'],
            'CAR_STSwh' => ['sts->issued','Кем выдан СТС'],
            'CAR_Col' => ['sts->color','Цвет автомобиля'],
            
            'CAR_PTSn' => ['pts->number','Серия и Номер ПТС'],
            'CAR_PTSd' => ['pts->dateDocumentText','дата выдачи ПТС'],
            'CAR_PTSwh' => ['pts->issued','Кем выдан ПТС'],
            
            'CAR_OSAGOn' => ['osago->number','Серия и Номер полиса ОСАГО'],
            
            'CAR_TAXLn' => ['license->number','Серия и Номер лицензии'],
            'CAR_TAXLsd' => ['license->dateDocumentText','Дата выдачи'],
            'CAR_TAXLed' => ['license->expirationText','Срок действия'],
            'CAR_TAXLotm' => ['license->marks','Особые отметки'],
            'CAR_TAXLotmQR' => ['license->marks','Особые отметки',['qr']],
            
            
            'CON_N' => ['number','Номер договора'],
            'CON_rnt' => ['price','Ставка аренды в сутки'],
            'CON_rntt' => ['','Ставка аренды в сутки',['text']],
            'CON_sd' => ['startText','Дата договора'],
            'CON_ed' => [
                'finishText',
                'Дата окончания договора'
            ],
        ]
];
