<?php

return [
        'variable' => [
            'SSE_ufaaddr' => array('subjectFrom->actualEntity->address','Адрес Местонахождения юр лица'),
            'SSE_umail' => array('command','Электронная почта'),
            'SSE_cnfu' => array('subjectFrom->actualEntity->fullName','Полное название организации'),
            'SSE_cnsh' => array('subjectFrom->actualEntity->fullName','Полное название организации'),
            'SSE_inn' => array('subjectFrom->actualEntity->inn','ИНН организации'),
            'SSE_ln' => array('subjectFrom->surname','Фамилия другие падежи'),
            'SSE_fn' => array('subjectFrom->name','Имя другие падежи'),
            'SSE_sn' => array('subjectFrom->patronymic','Отчество другие падежи'),
            'SSE_fns' => array('subjectFrom->fio','Сокращенная форма ФИО (Иванов И.И.)'),
            'SSE_ogrn' => array('subjectFrom->actualEntity->ogrn','ОГРН'),
            'SSE_uregaddr' => array('subjectFrom->actualEntity->address','Адрес регистрации юр лица'),
            'SSE_bd' => array('subjectFrom->birthday','Дата рождения'),
            'SSE_bp' => array('subjectFrom->actualPassport->birthplace','Место рождения'),
            'SSE_pasn' => array('subjectFrom->actualPassport->number','Серия и номер паспорта'),
            'SSE_pash' => array('subjectFrom->actualPassport->issuedBy','Кем выдан паспорт'),
            'SSE_pasd' => array('subjectFrom->actualPassport->dateIssued','Дата выдачи паспорта'),
            'SSE_pasc' => array('subjectFrom->actualPassport->code','Код подразделения паспорта'),
            'SSE_regaddrd' => array('subjectFrom->actualPassport->dateResidence','Дата регистрации'),
            'SSE_regaddr' => array('subjectFrom->actualPassport->placeResidence','Адрес регистрации'),
            'SSE_lisde' => array('subjectFrom->actuallicense->start','Срок действия водительского удостоверения'),
            'SSE_lisn' => array('subjectFrom->actuallicense->number','Серия и номер водительского удостоверения'),
            'SSE_lish' => array('subjectFrom->actuallicense->issuedBy','Кем выдано водительское удостоверение'),
            'SSE_lisd' => array('command','Дата выдачи водительского удостоверения'),
            'SSE_phone' => array('subjectFrom->actualContact->phone','Номер телефона'),
            'SSE_mail' => array('command','Элетронная почта'),
            'SSE_accn' => array('subjectFrom->actualPayment->checkingAccount','Номер счёта'),
            'SSE_babik' => array('subjectFrom->actualPayment->bankBik','БИК банка'),
            'SSE_baaddr' => array('subjectFrom->actualPayment->address','Юридический адрес'),
            'SSE_bainn' => array('subjectFrom->actualPayment->bankInn','ИНН банка'),
            'SSE_corrch' => array('subjectFrom->actualPayment->correspondentAccoun','к/сч'),
            'SSE_bafn' => array('subjectTo->actualPayment->name','Название филиала'),
            'SSE_ban' => array('subjectFrom->actualPayment->bankName','Наименование банка'),
            'SSE_ccn' => array('subjectFrom->payAccount->cardNumber','Номер карты'),
            
            'SCL_ufaaddr' => array('subjectTo->actualEntity->address','Адрес Местонахождения юр лица'),
            'SCL_umail' => array('command','Электронная почта'),
            'SCL_cn' => array('subjectTo->actualEntity->fullName','Название организацииы'),
            'SCL_ln' => array('subjectTo->surname','Фамилия арендатора другие падежи'),
            'SCL_fn' => array('subjectTo->name','Имя арендатора другие падежи'),
            'SCL_sn' => array('subjectTo->patronymic','Отчество арендатора другие падежи'),
            'SCL_fns' => array('subjectTo->fio','Сокращенная форма ФИО (Иванов И.И.)'),
            'SCL_bd' => array('subjectTo->birthdayText','Дата рождения арендатора'),
            'SCL_bp' => array('subjectTo->actualPassport->birthplace','Место рождения арендатора'),
            'SCL_pasn' => array('subjectTo->actualPassport->number','Серия и номер паспорта арендатора'),
            'SCL_pash' => array('subjectTo->actualPassport->issuedBy','Кем выдан паспорт'),
            'SCL_pasd' => array('subjectTo->actualPassport->dateIssuedText','Дата выдачи паспорта'),
            'SCL_pasc' => array('subjectTo->actualPassport->code','Код подразделения паспорта'),
            'SCL_regaddr' => array('subjectTo->actualPassport->placeResidence','Адрес регистрации арендатора'),
            'SCL_regaddrd' => array('subjectTo->actualPassport->dateResidenceText','Дата регистрации'),
            'SCL_addr' => array('subjectTo->actualPassport->placeResidence','Место жительства арендатора'),
            'SCL_lisn' => array('subjectTo->actuallicense->number','Серия и номер водительского удостоверения арендатора'),
            'SCL_lish' => array('subjectTo->actuallicense->issuedBy','Кем выдано водительское удостоверение'),
            'SCL_lisd' => array('subjectTo->actuallicense->startText','Дата выдачи водительского удостоверения'),
            'SCL_lisde' => array('subjectTo->actuallicense->finish','Срок действия водительского удостоверения'),
            'SCL_phone' => array('subjectTo->actualContact->phone','Номер телефона Арендатора'),
            'SCL_mail' => array('command','Элетронная почта арендатора'),
            'SCL_accn' => array('subjectTo->actualPayment->checkingAccount','Номер счёта арендатора'),
            'SCL_babik' => array('subjectTo->actualPayment->bankBik','БИК банка арендатора'),
            'SCL_corrch' => array('subjectTo->actualPayment->correspondentAccount','к/сч'),
            'SCL_bainn' => array('subjectTo->actualPayment->bankInn','ИНН банка'),
            'SCL_baaddr' => array('subjectTo->actualPayment->address','Юридический адрес'),
            'SCL_bafn' => array('subjectTo->actualPayment->name','Название филиала'),
            'SCL_ban' => array('subjectTo->actualPayment->bankName','Наименование банка арендатора'),
            'SCL_ccn' => array('subjectTo->payAccount->cardNumber','Номер карты арендатора'),
            'CAR_Brand' => array('car->generation->model->brand->name','Марка автомобиля'),
            'CAR_Model' => array('car->generation->model->name','Модель автомобиля'),
            'CAR_VIN' => array('car->vin','VIN номер автомобиля'),
            'CAR_Y' => array('car->year','Год выпуска автомобиля'),
            'CAR_Power' => array('car->hp','Мощность двигателя'),
            'CAR_StNum' => array('sts->regNumber','Регистрационный номер'),
            'CAR_STSd' => array('sts->dateDocumentText','Дата выдачи СТС'),
            'CAR_STSn' => array('sts->number','Серия и Номер СТС'),
            'CAR_STSwh' => array('sts->issued','Кем выдан СТС'),
            'CAR_Col' => array('sts->color','Цвет автомобиля'),

            
            
            'CAR_PTSn' => array('pts->number','Серия и Номер ПТС'),
            'CAR_PTSd' => array('pts->dateDocumentText','дата выдачи ПТС'),
            'CAR_PTSwh' => array('pts->issued','Кем выдан ПТС'),
            
            'CAR_OSAGOn' => array('osago->number','Серия и Номер полиса ОСАГО'),
            
            'CAR_TAXLn' => array('license->number','Серия и Номер лицензии'),
            'CAR_TAXLsd' => array('license->dateDocumentText','Дата выдачи'),
            'CAR_TAXLed' => array('license->expiration','Срок действия'),
            'CAR_TAXLotm' => array('license->marks','Особые отметки'),
            
            'CON_N' => array('number','Номер договора'),
            'CON_sd' => array('startText','Дата договора'),
            'CON_ed' => array('finishText','Дата окончания договора'),
        ]
];
